In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_excel('./spark_dataset.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194692 entries, 0 to 194691
Data columns (total 31 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   sparkid                    194692 non-null  int64
 1   inn                        194692 non-null  int64
 2   latitude                   194692 non-null  object
 3   longitude                  194692 non-null  object
 4   okved                      194692 non-null  object
 5   labourrange                194692 non-null  object
 6   employees2017              193545 non-null  float64
 7   employees2018              193983 non-null  float64
 8   employees2019              191933 non-null  float64
 9   bsform1field1110           14926 non-null   float64
 10  bsform1field1120           1184 non-null    float64
 11  bsform1field1600           194681 non-null  float64
 12  bsform2field2100           193095 non-null  float64
 13  bsform2field2110           193019 non-null  float64
 14  bsform2field2200           194630 non-null  float64
 15  bsform2field2300           194630 non-null  float64
 16  bsform2field2400           194590 non-null  float64
 17  bsform4field4121           56435 non-null   float64
 18  bsform4field4122           56938 non-null   float64
 19  medicinsurance2017         194105 non-null  float64
 20  medicinsurance2018         194405 non-null  float64
 21  pension2017                194326 non-null  float64
 22  pension2018                194593 non-null  float64
 23  socialins2017              191774 non-null  float64
 24  socialins2018              190860 non-null  float64
 25  trademarksnumber           194692 non-null  int64
 26  inventionsnumber           194692 non-null  int64
 27  industrialmodelsnumber     194692 non-null  int64
 28  applicationsoftwarenumber  194692 non-null  int64
 29  patentapplicationnumber    194692 non-null  int64
 30  Число непустых ячеек       194692 non-null  int64
dtypes: float64(19), int64(8), object(4)
memory usage: 46.0+ MB

In [4]:
df.head(50)

,sparkid,inn,latitude,longitude,okved,labourrange,employees2017,employees2018,employees2019,bsform1field1110,...,pension2017,pension2018,socialins2017,socialins2018,trademarksnumber,inventionsnumber,industrialmodelsnumber,applicationsoftwarenumber,patentapplicationnumber,Число непустых ячеек
0,72287,5008000202,"55,922314","37,526012",20.59.5,101 .. 150,133.0,138.0,132.0,237000.0,...,10913895.30,12187434.91,130290.01,NaN,1,1,0,0,0,26
1,8921,7714328921,"55,781234","37,57171",73.11,151 .. 200,166.0,168.0,164.0,NaN,...,44211488.57,46372505.50,789026.76,159789.13,3,0,0,0,0,28
2,72289,5034050168,"55,793478","38,934829",68.20.2,101 .. 150,101.0,114.0,121.0,NaN,...,8933351.88,12268445.45,339802.46,NaN,1,1,0,0,1,27
3,52838,7417001585,"55,03951","58,955023",42.11,201 .. 250,295.0,238.0,204.0,NaN,...,21203783.18,18891167.93,730273.46,283894.59,0,0,0,0,0,28
4,8923,5605000830,"51,487957","57,379",28.41.2,251 .. 500,302.0,277.0,263.0,0.0,...,10559716.37,14161486.95,2218.50,NaN,1,0,0,0,0,28
5,28334,2604000014,"45,357093","44,241412",49.41.2,6 .. 10,8.0,8.0,6.0,NaN,...,216313.83,252919.60,14112.88,6084.57,0,0,0,0,0,28
6,72291,5031024890,"55,800382","38,200059",21.10,51 .. 100,104.0,102.0,90.0,NaN,...,11273185.10,9235687.51,136871.56,85960.38,0,0,0,0,0,28
7,72292,5001000041,"55,801334","37,967272",20.11,251 .. 500,378.0,369.0,359.0,NaN,...,85400709.72,96293951.78,4806635.03,4149836.24,0,0,0,0,0,28
8,28337,2630016500,"44,23312","43,138931",49.4,0 .. 5,9.0,7.0,5.0,NaN,...,120874.97,122955.03,7433.68,1383.25,0,0,0,0,0,26
9,28338,2614003141,"44,752205","44,985077",49.41,51 .. 100,75.0,76.0,71.0,NaN,...,3086649.41,3480934.90,360294.42,450727.71,0,0,0,0,0,28
10,52843,7441006792,"54,37424","59,995066",52.21.22,11 .. 15,14.0,15.0,15.0,NaN,...,443492.60,510800.64,32581.26,43026.90,0,0,0,0,0,26
11,34237,5258011750,"56,29206","43,926743",68.20.2,11 .. 15,13.0,14.0,14.0,NaN,...,536957.00,622338.00,70779.00,76619.90,0,0,0,0,0,26
12,28340,2620000692,"44,262212","44,584496",01.11.1,16 .. 50,18.0,17.0,16.0,NaN,...,886395.42,1153356.20,72981.00,157395.03,0,0,0,0,0,28
13,52847,7433000941,"55,69864","61,541141",23.70,11 .. 15,22.0,25.0,12.0,NaN,...,1282276.52,1880400.00,134649.64,211900.00,0,0,0,0,0,26
14,28344,2605000433,"45,112714","43,417761",49.4,0 .. 5,1.0,1.0,1.0,NaN,...,28233.33,29392.00,3721.67,3874.40,0,0,0,0,0,28
15,8929,7711028704,"55,84973","37,507634",68.2,6 .. 10,8.0,8.0,8.0,NaN,...,738121.60,805200.00,97297.85,106140.00,0,0,0,0,0,28
16,28348,2617003118,"48,541508","41,088509",49.41.2,0 .. 5,3.0,3.0,1.0,NaN,...,63010.80,61556.71,4173.19,12469.38,0,0,0,0,0,28
17,34253,5216003162,"55,034101","43,248029",47.11,0 .. 5,9.0,5.0,1.0,NaN,...,220748.44,188924.77,29098.65,24209.62,0,0,0,0,0,26
18,72297,5036002480,"55,43154","37,575075",27.32,501 .. 1000,NaN,628.0,643.0,336000.0,...,NaN,82126269.84,NaN,564192.42,7,5,0,0,0,26
19,34254,5221003672,"55,032566","44,49199",47.1,0 .. 5,6.0,1.0,0.0,NaN,...,142773.18,141055.10,20532.61,17526.19,0,0,0,0,0,26
20,52854,7416002346,"54,369187","60,799455",42.11,0 .. 5,3.0,2.0,2.0,NaN,...,180162.78,191985.77,23744.79,25307.21,0,0,0,0,0,28
21,34258,4028025884,"54,541117","36,268544",46.15.1,0 .. 5,5.0,3.0,2.0,NaN,...,74185.02,59794.81,9778.94,9473.24,0,0,0,0,0,26
22,72298,5038011787,"56,059557","37,85875",26.51.4,6 .. 10,5.0,3.0,3.0,NaN,...,2655166.77,2911114.81,159932.98,199524.34,0,4,0,0,1,28
23,8936,2508012923,"42,794103","132,870729",52.29,5000 √Р¬Є √Р¬±√Р¬Њ√Р¬ї√Р¬µ√Р¬µ,251.0,274.0,286.0,NaN,...,9095151.95,13764723.19,665386.94,2281457.16,0,0,0,0,0,28
24,28365,6517000520,"50,857524","142,661411",10.71,51 .. 100,80.0,76.0,75.0,NaN,...,6505224.83,6887771.79,42521.31,102066.42,0,0,0,0,0,26
25,72299,5036008813,"55,425967","37,588477",27.32,251 .. 500,367.0,358.0,396.0,374000.0,...,43477456.02,51522882.35,1822877.48,1776795.48,3,10,0,0,0,29
26,34263,4416000223,"57,876888","43,791518",47.11,6 .. 10,10.0,8.0,8.0,NaN,...,280857.32,210478.30,30503.58,17847.41,0,0,0,0,0,26
27,52861,5007081713,"56,34507","37,520072",52.21.22,101 .. 150,177.0,147.0,128.0,NaN,...,17028945.14,19039033.75,112036.24,NaN,0,0,0,0,0,27
28,72300,5017008127,"55,923744","36,821686",72.19,0 .. 5,1.0,1.0,1.0,NaN,...,326915.81,356572.36,26376.02,10674.47,0,0,0,0,0,28
29,72301,5031002293,"55,861422","38,583704",17.12,251 .. 500,371.0,364.0,361.0,NaN,...,26286549.25,28376579.66,1157699.77,1008453.76,0,7,0,0,5,28
30,52863,6149012940,"48,911026","40,41727",42.11,6 .. 10,14.0,6.0,7.0,NaN,...,125526.59,103231.65,16547.16,14407.34,0,0,0,0,0,26
31,28370,1102047120,"63,551784","53,691074",71.12.3,0 .. 5,35.0,7.0,0.0,NaN,...,4111574.43,5143236.09,11693.22,107822.11,0,0,0,0,0,28
32,72304,5078008124,"56,723392","37,622641",25.11,151 .. 200,170.0,191.0,186.0,NaN,...,14154574.48,17675391.91,1122287.46,610550.76,0,0,0,0,0,28
33,52864,6147037522,"48,256419","40,427804",42.11,51 .. 100,63.0,63.0,66.0,NaN,...,3181994.85,4180516.23,429801.50,556834.52,0,0,0,0,0,28
34,34279,5405225611,"55,024829","82,987787",68.20.2,0 .. 5,1.0,1.0,1.0,NaN,...,63560.52,63888.95,8378.43,8421.73,0,0,0,0,0,26
35,8941,3903004724,"54,693308","20,456711",49.4,0 .. 5,17.0,5.0,4.0,NaN,...,437385.75,257995.72,57655.40,34008.53,0,0,0,0,0,29
36,72305,5032001285,"55,667238","37,276287",68.20.2,6 .. 10,9.0,9.0,9.0,NaN,...,516674.83,559329.28,62678.28,73729.77,0,0,0,0,0,28
37,8942,5190146332,"68,963769","33,058063",52.24,501 .. 1000,560.0,511.0,NaN,19000.0,...,53411660.77,68154550.80,1079589.00,1302936.19,1,0,0,0,0,28
38,72309,5038010790,"56,013519","37,825675",68.20.2,11 .. 15,12.0,14.0,12.0,NaN,...,1223702.44,1493445.78,30395.99,159651.45,0,0,0,0,0,28
39,52869,3327848404,"56,112067","40,333268",52.21.22,201 .. 250,NaN,163.0,240.0,NaN,...,10822045.62,24412574.65,511338.22,1855901.94,0,0,0,0,0,27
40,52870,3338006713,"56,246362","42,139465",52.21.22,251 .. 500,28.0,11.0,422.0,NaN,...,4166666.20,14017053.36,508104.82,1687982.52,0,0,0,0,0,26
41,72315,1001315510,"61,741583","34,449242",25.11,151 .. 200,161.0,165.0,175.0,NaN,...,12286805.91,16718974.94,573270.58,1212910.26,0,0,0,0,0,28
42,28380,4617004838,"51,650541","35,978664",71.12.3,0 .. 5,12.0,5.0,5.0,NaN,...,391401.12,247191.23,42881.23,22823.53,0,0,0,0,0,26
43,34306,6454115765,"51,518344","46,017016",68.20,0 .. 5,7.0,6.0,5.0,NaN,...,118245.42,121348.06,15560.27,10895.02,0,0,0,0,0,26
44,52874,5044086420,"56,072946","37,126969",52.21.22,16 .. 50,24.0,30.0,33.0,NaN,...,3534847.67,4224263.76,NaN,395357.71,0,0,0,0,0,27
45,28383,275016943,"54,683227","55,796047",71.12.3,16 .. 50,NaN,NaN,26.0,NaN,...,4418720.18,10891628.32,76182.61,218118.74,0,0,0,0,0,26
46,34310,6455031540,"51,557982","46,051061",47.52.7,0 .. 5,16.0,2.0,2.0,NaN,...,414302.00,216304.00,59206.22,8592.62,0,0,0,0,0,26
47,52880,3430009480,"48,619321","42,841888",52.21.22,0 .. 5,84.0,55.0,1.0,NaN,...,4543582.43,4243133.76,416011.55,219545.52,0,0,0,0,0,28
48,72324,6205100110,"55,130867","40,176037",42.11,11 .. 15,16.0,13.0,13.0,NaN,...,551378.52,536241.15,67086.25,18102.03,0,0,0,0,0,26
49,8960,6501009502,"46,959468","142,730564",68.20.2,0 .. 5,4.0,5.0,3.0,NaN,...,1051128.00,1211861.00,93577.00,97173.00,0,0,0,0,0,26