In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('../ecology.xlsx')
df.head()

,id,a4a,a6a,a2,a0,b1,b5,b7a,d1a1x,g1a,...,BMGc23i,BMGc23j,BMGc24,BMGc25,BMGc27,BMGd6,BMGd7,BMGe1,BMGe2,BMGe2u
0,22,Готовые Металлические Изделия,Малый,Центральный Федеральный округ,Производство,Акционерная компания с неторгуемыми акциями ил...,2007,Нет,Производство Готовых Строительных Металлически...,0,...,Да,Нет,Модернизация машин и оборудования,Да,NaN,Нет,Нет,100000,20000,Литры
1,29,Машины и оборудование,Крупный,Центральный Федеральный округ,Производство,Акционерная компания с неторгуемыми акциями ил...,2002,Нет,Производство Насосов И Компрессоров,0,...,Нет,Нет,Модернизация машин и оборудования,Нет,Не является приоритетом по сравнению с другими...,Нет,Нет,160000,18500,Литры
2,34,Другое Производство,Средний,Центральный Федеральный округ,Производство,Акционерная компания с неторгуемыми акциями ил...,2005,Нет,"Производство Алюминиевых И Медных Проводов, Си...",100,...,Да,Не знаю,NaN,Нет,Нехватка финансовых ресурсов,Нет,Нет,Не знаю,Не знаю,NaN
3,50,Готовые Металлические Изделия,Малый,Центральный Федеральный округ,Другие услуги,Акционерная компания с неторгуемыми акциями ил...,2015,Нет,Строительство жилых и нежилых зданий,0,...,Нет,Нет,NaN,Нет,Операционный и/ или технический риск,Нет,Нет,Не знаю,Не знаю,NaN
4,56,Другие Услуги,Малый,Центральный Федеральный округ,Другие услуги,Акционерная компания с неторгуемыми акциями ил...,2002,Нет,Оптовая Продажа Офисной Мебели,0,...,Да,Не применимо,Модернизация машин и оборудования,Нет,Нехватка финансовых ресурсов,Нет,Нет,100000,10000,Литры

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1323 entries, 0 to 1322
Data columns (total 48 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   1323 non-null   int64
 1   a4a                  1323 non-null   object
 2   a6a                  1323 non-null   object
 3   a2                   1323 non-null   object
 4   a0                   1323 non-null   object
 5   b1                   1323 non-null   object
 6   b5                   1323 non-null   object
 7   b7a                  1323 non-null   object
 8   d1a1x                1323 non-null   object
 9   g1a                  1323 non-null   object
 10  BMj4c                1323 non-null   object
 11  j30_environment_pos  1323 non-null   int64
 12  BMj5                 1323 non-null   object
 13  n2a                  1323 non-null   object
 14  n2e                  889 non-null    object
 15  n2b                  1323 non-null   object
 16  n2f                  1323 non-null   object
 17  n2i                  152 non-null    object
 18  n2p                  889 non-null    object
 19  BMGa1                1323 non-null   object
 20  BMGa2                1323 non-null   object
 21  BMGa4                1323 non-null   object
 22  BMGb1                1323 non-null   object
 23  BMGb2                1323 non-null   object
 24  BMGc2                781 non-null    object
 25  BMGc5                471 non-null    object
 26  BMGc7                1323 non-null   object
 27  BMGc8                166 non-null    object
 28  BMGc16               1323 non-null   object
 29  BMGc18               1323 non-null   object
 30  BMGc23a              1323 non-null   object
 31  BMGc23b              1323 non-null   object
 32  BMGc23c              1323 non-null   object
 33  BMGc23d              1323 non-null   object
 34  BMGc23e              1323 non-null   object
 35  BMGc23f              1323 non-null   object
 36  BMGc23g              1323 non-null   object
 37  BMGc23h              1323 non-null   object
 38  BMGc23i              1323 non-null   object
 39  BMGc23j              1323 non-null   object
 40  BMGc24               671 non-null    object
 41  BMGc25               1323 non-null   object
 42  BMGc27               876 non-null    object
 43  BMGd6                1323 non-null   object
 44  BMGd7                1323 non-null   object
 45  BMGe1                1323 non-null   object
 46  BMGe2                1323 non-null   object
 47  BMGe2u               194 non-null    object
dtypes: int64(2), object(46)
memory usage: 496.3+ KB

In [9]:
df2 = df[['a4a', 'a6a', 'a2', 'b5', 'b7a', 'BMj4c', 'n2a', 'n2e', 'n2b', 'n2f', 'BMGa2', 'BMGa2', 'BMGc23a', 'BMGc23c', 'BMGc23d', 'BMGc23e', 'BMGc23g', 'BMGc25', 'BMGe1']]

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1323 entries, 0 to 1322
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       1323 non-null   int64
 1   a4a      1323 non-null   object
 2   a6a      1323 non-null   object
 3   a2       1323 non-null   object
 4   b5       1323 non-null   object
 5   b7a      1323 non-null   object
 6   BMj4c    1323 non-null   object
 7   n2a      1323 non-null   object
 8   n2e      889 non-null    object
 9   n2b      1323 non-null   object
 10  n2f      1323 non-null   object
 11  BMGa2    1323 non-null   object
 12  BMGa2    1323 non-null   object
 13  BMGc23a  1323 non-null   object
 14  BMGc23c  1323 non-null   object
 15  BMGc23d  1323 non-null   object
 16  BMGc23e  1323 non-null   object
 17  BMGc23g  1323 non-null   object
 18  BMGc25   1323 non-null   object
 19  BMGe1    1323 non-null   object
dtypes: int64(1), object(19)
memory usage: 206.8+ KB

In [10]:
df2.to_excel('~/downloads/ecology_for_interview.xlsx')